# LocalOrz
VERSION = '0.1 dev'

# Problem Status
UNKNOWN = 'Unknown'
NORMAL = 'Normal'
COMPILATION_ERROR = 'Compilation Error'
PROBLEM_STATUS = (UNKNOWN, NORMAL, COMPILATION_ERROR)

# Testcase Status
ACCEPTED = 'Accepted'
WRONG_ANSWER = 'Wrong Answer'
PARTLY_ACCEPTED = 'Partly Accepted'
CANNOT_EXECUTE = 'Cannot Execute'
TIME_LIMIT_EXCEEDED = 'Time Limit Exceeded'
MEMORY_LIMIT_EXCEEDED = 'Memory Limit Exceeded'
RUNTIME_ERROR = 'Runtime Error'
PROGRAM_NO_OUTPUT = 'Program No Output'
NO_SOURCE_FILE = 'No Source File'
NO_STANDARD_INPUT = 'No Standard Input'
NO_STANDARD_OUTPUT = 'No Standard Output'
SPECIAL_JUDGE_ERROR = 'Special Judge Error'
TESTCASE_STATUS = (ACCEPTED, WRONG_ANSWER, PARTLY_ACCEPTED, CANNOT_EXECUTE, TIME_LIMIT_EXCEEDED, MEMORY_LIMIT_EXCEEDED, RUNTIME_ERROR, PROGRAM_NO_OUTPUT, NO_SOURCE_FILE, NO_STANDARD_INPUT, NO_STANDARD_OUTPUT, SPECIAL_JUDGE_ERROR, COMPILATION_ERROR)

# Checker
NORMAL_JUDGE = 'Normal Judge'
FLOAT_JUDGE = 'Float Judge'
SPECIAL_JUDGE = 'Special Judge'
CHECKER = [NORMAL_JUDGE, FLOAT_JUDGE, SPECIAL_JUDGE]
